# Initial Generation

In [15]:
import pandas as pd

# Define all valid user input options
features = {
    "AgeGroup": ["18–29", "30–44", "45+"],
    "HairLoss": ["Yes", "No"],
    "Dandruff": ["Yes", "No"],
    "HairGreying": ["Yes", "No"],
    "HL_Duration": ["<3 months", "3–6 months", ">6 months"],
    "HL_Shedding": ["Rarely", "Occasionally", "Frequently"],
    "DF_Type": ["Powdery", "Flaky"],
    "DF_ItchyScalp": ["Rarely", "Frequently"],
    "GR_Duration": ["<3 months", "3-12", ">12"],
    "GR_TreatmentType": ["Coloring/Keratin", "None"],
    "RegularUsage": ["Yes", "No"],
    "WashFrequency": ["Rarely", "2–3 times/week", "Frequently"],
    "TakesSupplements": ["Yes", "No"],
    "StressLevel": ["Rarely", "Occasionally", "Frequently"],
    "FamilyHistory": ["Yes", "No"],
}

# Collect all logical user responses
logical_responses = []

# Generate combinations logically
for age in features["AgeGroup"]:
    for wash in features["WashFrequency"]:
        for supp in features["TakesSupplements"]:
            for stress in features["StressLevel"]:
                for fam in features["FamilyHistory"]:
                        
                        for hl in features["HairLoss"]:
                            if hl == "Yes":
                                for hl_dur in features["HL_Duration"]:
                                    for shed in features["HL_Shedding"]:
                                        hl_duration = hl_dur
                                        hl_shedding = shed
                            else:
                                hl_duration = "None"
                                hl_shedding = "None"

                            for df in features["Dandruff"]:
                                if df == "Yes":
                                    for d_type in features["DF_Type"]:
                                        for itch in features["DF_ItchyScalp"]:
                                            df_type = d_type
                                            df_itch = itch
                                            
                                            for gr in features["HairGreying"]:
                                                if gr == "Yes":
                                                    for gr_dur in features["GR_Duration"]:
                                                        for treat in features["GR_TreatmentType"]:
                                                            for usage in features["RegularUsage"]:
                                                                logical_responses.append({
                                                                    "AgeGroup": age,
                                                                    "HairLoss": hl,
                                                                    "HL_Duration": hl_duration,
                                                                    "HL_Shedding": hl_shedding,
                                                                    "Dandruff": df,
                                                                    "DF_Type": df_type,
                                                                    "DF_ItchyScalp": df_itch,
                                                                    "HairGreying": gr,
                                                                    "GR_Duration": gr_dur,
                                                                    "GR_TreatmentType": treat,
                                                                    "RegularUsage": usage,
                                                                    "WashFrequency": wash,
                                                                    "TakesSupplements": supp,
                                                                    "StressLevel": stress,
                                                                    "FamilyHistory": fam,
                                                                })
                                                else:
                                                    logical_responses.append({
                                                        "AgeGroup": age,
                                                        "HairLoss": hl,
                                                        "HL_Duration": hl_duration,
                                                        "HL_Shedding": hl_shedding,
                                                        "Dandruff": df,
                                                        "DF_Type": df_type,
                                                        "DF_ItchyScalp": df_itch,
                                                        "HairGreying": gr,
                                                        "GR_Duration": "None",
                                                        "GR_TreatmentType": "None",
                                                        "RegularUsage": "No",
                                                        "WashFrequency": wash,
                                                        "TakesSupplements": supp,
                                                        "StressLevel": stress,
                                                        "FamilyHistory": fam,
                                                    })
                                else:
                                    df_type = "None"
                                    df_itch = "None"
                                    for gr in features["HairGreying"]:
                                        if gr == "Yes":
                                            for gr_dur in features["GR_Duration"]:
                                                for treat in features["GR_TreatmentType"]:
                                                    for usage in features["RegularUsage"]:
                                                        logical_responses.append({
                                                            "AgeGroup": age,
                                                            "HairLoss": hl,
                                                            "HL_Duration": hl_duration,
                                                            "HL_Shedding": hl_shedding,
                                                            "Dandruff": df,
                                                            "DF_Type": df_type,
                                                            "DF_ItchyScalp": df_itch,
                                                            "HairGreying": gr,
                                                            "GR_Duration": gr_dur,
                                                            "GR_TreatmentType": treat,
                                                            "RegularUsage": usage,
                                                            "WashFrequency": wash,
                                                            "TakesSupplements": supp,
                                                            "StressLevel": stress,
                                                            "FamilyHistory": fam,
                                                        })
                                        else:
                                            logical_responses.append({
                                                "AgeGroup": age,
                                                "HairLoss": hl,
                                                "HL_Duration": hl_duration,
                                                "HL_Shedding": hl_shedding,
                                                "Dandruff": df,
                                                "DF_Type": df_type,
                                                "DF_ItchyScalp": df_itch,
                                                "HairGreying": gr,
                                                "GR_Duration": "None",
                                                "GR_TreatmentType": "None",
                                                "RegularUsage": "No",
                                                "WashFrequency": wash,
                                                "TakesSupplements": supp,
                                                "StressLevel": stress,
                                                "FamilyHistory": fam,
                                            })

# Convert to DataFrame
df = pd.DataFrame(logical_responses)
print("user response rows generated:", len(df))
df.to_csv("user_responses_.csv", index=False)

user response rows generated: 14040

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.sample(5)

,AgeGroup,HairLoss,HL_Duration,HL_Shedding,Dandruff,DF_Type,DF_ItchyScalp,HairGreying,GR_Duration,GR_TreatmentType,RegularUsage,WashFrequency,TakesSupplements,StressLevel,FamilyHistory
1932,18–29,No,None,None,Yes,Flaky,Frequently,Yes,>12,Coloring/Keratin,Yes,2–3 times/week,Yes,Occasionally,Yes
1785,18–29,No,None,None,Yes,Flaky,Rarely,Yes,3-12,Coloring/Keratin,Yes,2–3 times/week,Yes,Rarely,No
10770,45+,No,None,None,Yes,Flaky,Frequently,Yes,3-12,None,Yes,Rarely,No,Frequently,Yes
11556,45+,No,None,None,Yes,Flaky,Frequently,No,None,None,No,2–3 times/week,Yes,Frequently,Yes
1319,18–29,Yes,>6 months,Frequently,Yes,Powdery,Frequently,Yes,3-12,None,Yes,Rarely,No,Frequently,Yes

In [19]:
import pandas as pd

# Load the user response data
df = pd.read_csv("user_responses_.csv")

# Initialize target columns
df["Primary_HL"] = None
df["Support_HL"] = None
df["Lifestyle_HL"] = None
df["Primary_DF"] = None
df["Support_DF"] = None
df["Lifestyle_DF"] = None
df["Primary_GR"] = None

# ---------------------------- HAIR LOSS PRODUCTS ----------------------------

# Primary_HL mapping
def map_primary_hl(row):
    if row["HairLoss"] == "Yes":
        duration = row["HL_Duration"]
        age = row["AgeGroup"]
        stress = row["StressLevel"]
        fh = row["FamilyHistory"]

        if duration == "<3 months":
            return "Biotin Gummies (Nutrafol Growth Activator)"
        elif duration == "3–6 months":
            if fh == "Yes" and stress == "Frequently":
                return "Minoxidil + Redensyl + DHT Blocker (ManMatters Advanced)"
            elif fh == "Yes" and stress == "Rarely":
                return "Minoxidil 2% + Biotin + Saw Palmetto Serum (Mars by GHC)"
            else:
                return "Minoxidil 2% + Biotin Gummies (Rogaine, Viviscal)"
        elif duration == ">6 months":
            if age == "18–29":
                if fh == "Yes" and stress == "Frequently":
                    return "Redensyl + Derma Roller + Biotin Spray (Pilgrim, Minimalist)"
                elif fh == "Yes" and stress == "Rarely":
                    return "Redensyl + Biotin + Mild Minoxidil (Pilgrim, Be Bodywise)"
                else:
                    return "Redensyl + Biotin Combo Serum"
            elif age == "30–44":
                if fh == "Yes" and stress == "Frequently":
                    return "Minoxidil 5% + PRP Kit + Redensyl (ManMatters)"
                elif fh == "Yes" and stress == "Rarely":
                    return "Minoxidil 5% Foam + Redensyl (Keeps, Pilgrim)"
                else:
                    return "Minoxidil 5% Foam + Redensyl + Microneedling"
            elif age == "45+":
                if fh == "Yes" and stress == "Frequently":
                    return "Clinical Hair Regrowth Pack (Indulekha + Multivitamin + PRP)"
                elif fh == "Yes" and stress == "Rarely":
                    return "Redensyl + Biotin + Derma Roller Kit (MD Factor, Pilgrim)"
                else:
                    return "Advanced Hair Regrowth Kit (Indulekha / MD Factor)"
    return None

df["Primary_HL"] = df.apply(map_primary_hl, axis=1)

# Support_HL mapping
support_hl_map = {
    "Rarely": "Rosemary Oil Shampoo (Mamaearth)",
    "Occasionally": "Onion Scalp Serum (Wow)",
    "Frequently": "Anti–Shedding Hair Serum (Pilgrim)"
}
df["Support_HL"] = df["HL_Shedding"].map(support_hl_map)

# Lifestyle_HL mapping
def map_lifestyle_hl(row):
    if row["HairLoss"] == "Yes":
        if row["FamilyHistory"] == "Yes" and row["StressLevel"] == "Frequently":
            return "Ashwagandha Gummies / Stress B–Complex (Himalaya / Olly)"
        elif row["FamilyHistory"] == "Yes":
            return "Mild Daily Biotin + Scalp Nourishing Oil (Be Bodywise, Satthwa)"
    return None

df["Lifestyle_HL"] = df.apply(map_lifestyle_hl, axis=1)

# ---------------------------- DANDRUFF PRODUCTS ----------------------------

# Primary_DF mapping
primary_df_map = {
    "Powdery": "Tea Tree Oil Shampoo (Body Shop)",
    "Flaky": "Nizoral A–D / T–Gel (Neutrogena)"
}
df["Primary_DF"] = df["DF_Type"].map(primary_df_map)

# Support_DF mapping
support_df_map = {
    "Rarely": "Herbal Cleanser (Khadi Neem)",
    "Frequently": "Ketoconazole + Zinc Pyrithione (Sebamed, H&S Clinical)"
}
df["Support_DF"] = df["DF_ItchyScalp"].map(support_df_map)

# Lifestyle_DF mapping
def map_lifestyle_df(row):
    if row["DF_Type"] == "Powdery" and row["WashFrequency"] == "Rarely":
        return "Anti-fungal Herbal Shampoo (Selsun, Himalaya)"
    elif row["DF_Type"] == "Flaky" and row["WashFrequency"] == "Rarely":
        return "Clarifying Shampoo (Neutrogena)"
    elif row["DF_Type"] == "Flaky" and row["WashFrequency"] == "Frequently":
        return "Coal Tar / Salicylic Shampoo (MG217, Tarsum)"
    elif row["DF_Type"] == "Powdery" and row["WashFrequency"] == "Frequently":
        return "Tea Tree + Zinc Combo (Body Shop + DermaZinc)"
    return None

df["Lifestyle_DF"] = df.apply(map_lifestyle_df, axis=1)

# ---------------------------- HAIR GREYING PRODUCTS ----------------------------

# Primary_GR mapping
def map_primary_gr(row):
    if row["HairGreying"] == "Yes":
        dur = row["GR_Duration"]
        treat = row["GR_TreatmentType"]
        age = row["AgeGroup"]
        
        if dur == "<3 months":
            return "Melanin Boosting Shampoo (Just Herbs) + Diet Fix"
        elif dur == "<1 year":
            if treat == "Coloring/Keratin":
                return "Vitamin B12 + Amla Oil Routine (Kesh King, SoulTree)"
            else:
                return "Grey Hair Reverse Kit (Rogan, Curlvana)"
        elif dur == "<1.5 years":
            if age == "18–29":
                return "Herbal Hair Darkening Mask + Vitamin Support (Ayuga, Satthwa)"
            elif age == "30–44":
                return "Premature Greying Solution Pack (Traya, Be Bodywise)"
            else:
                return "Melanin + Biotin Combo Pack (HealthKart, Olly)"
    return None

df["Primary_GR"] = df.apply(map_primary_gr, axis=1)

# ---------------------------- SAVE TO CSV ----------------------------
df.to_csv("responses_with_targets.csv", index=False)
print("responses_with_targets.csv")

responses_with_targets.csv

In [21]:
hair_data = pd.read_csv("/Users/sakshisingh/Sakshi/Projects/HairVise-Product-Recommendation-main/fresh/responses_with_targets.csv")
hair_data.sample(10)

,AgeGroup,HairLoss,HL_Duration,HL_Shedding,Dandruff,DF_Type,DF_ItchyScalp,HairGreying,GR_Duration,GR_TreatmentType,...,TakesSupplements,StressLevel,FamilyHistory,Primary_HL,Support_HL,Lifestyle_HL,Primary_DF,Support_DF,Lifestyle_DF,Primary_GR
10898,45+,No,NaN,NaN,Yes,Flaky,Frequently,Yes,3-12,Coloring/Keratin,...,No,Frequently,No,NaN,NaN,NaN,Nizoral A–D / T–Gel (Neutrogena),"Ketoconazole + Zinc Pyrithione (Sebamed, H&S C...",Clarifying Shampoo (Neutrogena),NaN
4453,18–29,Yes,>6 months,Frequently,Yes,Flaky,Rarely,Yes,3-12,NaN,...,No,Frequently,Yes,Redensyl + Derma Roller + Biotin Spray (Pilgri...,Anti–Shedding Hair Serum (Pilgrim),Ashwagandha Gummies / Stress B–Complex (Himala...,Nizoral A–D / T–Gel (Neutrogena),Herbal Cleanser (Khadi Neem),"Coal Tar / Salicylic Shampoo (MG217, Tarsum)",NaN
2341,18–29,Yes,>6 months,Frequently,Yes,Powdery,Rarely,Yes,<3 months,Coloring/Keratin,...,No,Rarely,Yes,"Redensyl + Biotin + Mild Minoxidil (Pilgrim, B...",Anti–Shedding Hair Serum (Pilgrim),Mild Daily Biotin + Scalp Nourishing Oil (Be B...,Tea Tree Oil Shampoo (Body Shop),Herbal Cleanser (Khadi Neem),NaN,Melanin Boosting Shampoo (Just Herbs) + Diet Fix
10058,45+,Yes,>6 months,Frequently,Yes,Flaky,Frequently,Yes,>12,Coloring/Keratin,...,Yes,Frequently,No,Advanced Hair Regrowth Kit (Indulekha / MD Fac...,Anti–Shedding Hair Serum (Pilgrim),NaN,Nizoral A–D / T–Gel (Neutrogena),"Ketoconazole + Zinc Pyrithione (Sebamed, H&S C...",Clarifying Shampoo (Neutrogena),NaN
11936,45+,No,NaN,NaN,Yes,Flaky,Frequently,Yes,<3 months,NaN,...,No,Rarely,No,NaN,NaN,NaN,Nizoral A–D / T–Gel (Neutrogena),"Ketoconazole + Zinc Pyrithione (Sebamed, H&S C...",NaN,Melanin Boosting Shampoo (Just Herbs) + Diet Fix
10369,45+,No,NaN,NaN,Yes,Flaky,Rarely,Yes,>12,Coloring/Keratin,...,No,Rarely,No,NaN,NaN,NaN,Nizoral A–D / T–Gel (Neutrogena),Herbal Cleanser (Khadi Neem),Clarifying Shampoo (Neutrogena),NaN
5819,30–44,No,NaN,NaN,Yes,Flaky,Rarely,Yes,>12,Coloring/Keratin,...,No,Occasionally,Yes,NaN,NaN,NaN,Nizoral A–D / T–Gel (Neutrogena),Herbal Cleanser (Khadi Neem),Clarifying Shampoo (Neutrogena),NaN
6525,30–44,Yes,>6 months,Frequently,Yes,Powdery,Frequently,No,NaN,NaN,...,Yes,Occasionally,Yes,Minoxidil 5% Foam + Redensyl + Microneedling,Anti–Shedding Hair Serum (Pilgrim),Mild Daily Biotin + Scalp Nourishing Oil (Be B...,Tea Tree Oil Shampoo (Body Shop),"Ketoconazole + Zinc Pyrithione (Sebamed, H&S C...",NaN,NaN
10168,45+,Yes,>6 months,Frequently,Yes,Flaky,Rarely,Yes,<3 months,NaN,...,No,Rarely,Yes,Redensyl + Biotin + Derma Roller Kit (MD Facto...,Anti–Shedding Hair Serum (Pilgrim),Mild Daily Biotin + Scalp Nourishing Oil (Be B...,Nizoral A–D / T–Gel (Neutrogena),Herbal Cleanser (Khadi Neem),Clarifying Shampoo (Neutrogena),Melanin Boosting Shampoo (Just Herbs) + Diet Fix
4288,18–29,No,NaN,NaN,No,NaN,NaN,Yes,>12,NaN,...,No,Occasionally,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
hair_data.duplicated().sum()

np.int64(0)

In [25]:
hair_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14040 entries, 0 to 14039
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   AgeGroup          14040 non-null  object
 1   HairLoss          14040 non-null  object
 2   HL_Duration       7020 non-null   object
 3   HL_Shedding       7020 non-null   object
 4   Dandruff          14040 non-null  object
 5   DF_Type           11232 non-null  object
 6   DF_ItchyScalp     11232 non-null  object
 7   HairGreying       14040 non-null  object
 8   GR_Duration       12960 non-null  object
 9   GR_TreatmentType  6480 non-null   object
 10  RegularUsage      14040 non-null  object
 11  WashFrequency     14040 non-null  object
 12  TakesSupplements  14040 non-null  object
 13  StressLevel       14040 non-null  object
 14  FamilyHistory     14040 non-null  object
 15  Primary_HL        7020 non-null   object
 16  Support_HL        7020 non-null   object
 17  Lifestyle_HL      3510 non-null   object
 18  Primary_DF        11232 non-null  object
 19  Support_DF        11232 non-null  object
 20  Lifestyle_DF      7488 non-null   object
 21  Primary_GR        4320 non-null   object
dtypes: object(22)
memory usage: 2.4+ MB

In [29]:
hair_data.isnull().sum()

AgeGroup                0
HairLoss                0
HL_Duration          7020
HL_Shedding          7020
Dandruff                0
DF_Type              2808
DF_ItchyScalp        2808
HairGreying             0
GR_Duration          1080
GR_TreatmentType     7560
RegularUsage            0
WashFrequency           0
TakesSupplements        0
StressLevel             0
FamilyHistory           0
Primary_HL           7020
Support_HL           7020
Lifestyle_HL        10530
Primary_DF           2808
Support_DF           2808
Lifestyle_DF         6552
Primary_GR           9720
dtype: int64

# Generation with Noise

In [1]:
import pandas as pd
import random
from tqdm import tqdm
import numpy as np

# 1. Define feature space
features = {
    "AgeGroup": ["18–29", "30–44", "45+"],
    "HairLoss": ["Yes", "No"],
    "Dandruff": ["Yes", "No"],
    "HairGreying": ["Yes", "No"],
    "HL_Duration": ["<3 months", "3–6 months", ">6 months"],
    "HL_Shedding": ["Rarely", "Occasionally", "Frequently"],
    "DF_Type": ["Powdery", "Flaky"],
    "DF_ItchyScalp": ["Rarely", "Frequently"],
    "GR_Duration": ["<3 months", "<1 year", "<1.5 years"],
    "GR_TreatmentType": ["Coloring/Keratin", "None"],
    "RegularUsage": ["Yes", "No"],
    "WashFrequency": ["Rarely", "2–3 times/week", "Frequently"],
    "TakesSupplements": ["Yes", "No"],
    "StressLevel": ["Rarely", "Occasionally", "Frequently"],
    "FamilyHistory": ["Yes", "No"]
}

# 2. Sample generation
def generate_user_response():
    response = {key: random.choice(val) for key, val in features.items()}
    return response

# 3. Product mapping based on decision logic
def map_products(user):
    # Primary HL
    if user["HairLoss"] == "Yes":
        if user["HL_Duration"] == "<3 months":
            primary_hl = "Redensyl + Biotin Combo Serum"
            support_hl = "Shampoo + Conditioner for Hairfall"
        elif user["HL_Duration"] == "3–6 months":
            primary_hl = "Redensyl + Biotin + Mild Minoxidil (Pilgrim, Be Bodywise)"
            support_hl = "DHT Blocker Shampoo + Conditioner"
        else:
            primary_hl = "Minoxidil 5% Foam + Redensyl + Microneedling"
            support_hl = "DHT Blocker + Supplements"
        lifestyle_hl = "Scalp Massage, Diet Improvement"

    else:
        primary_hl = support_hl = lifestyle_hl = "Not Applicable"

    # Primary DF
    if user["Dandruff"] == "Yes":
        if user["DF_Type"] == "Powdery" and user["DF_ItchyScalp"] == "Frequently":
            primary_df = "Ketoconazole + Salicylic Acid Shampoo"
            support_df = "Tea Tree Scalp Serum"
        else:
            primary_df = "ZPTO + pH Balancing Anti-Dandruff Shampoo"
            support_df = "Aloe Vera + Niacinamide Serum"
        lifestyle_df = "Avoid Hot Water, Gentle Shampoo"

    else:
        primary_df = support_df = lifestyle_df = "Not Applicable"

    # Primary GR
    if user["HairGreying"] == "Yes":
        if user["GR_TreatmentType"] == "Coloring/Keratin":
            primary_gr = "Hair Strengthening Oil + Amla Tablets"
        elif user["GR_Duration"] == "<3 months":
            primary_gr = "Vitamin B12 + Biotin Gummies"
        elif user["GR_Duration"] == "<1 year":
            primary_gr = "Melanin Boost Hair Oil"
        else:
            primary_gr = "Anti-Grey Hair Serum + Vitamin Supplements"
    else:
        primary_gr = "Not Applicable"

    return {
        "Primary_HL": primary_hl,
        "Support_HL": support_hl,
        "Lifestyle_HL": lifestyle_hl,
        "Primary_DF": primary_df,
        "Support_DF": support_df,
        "Lifestyle_DF": lifestyle_df,
        "Primary_GR": primary_gr
    }

# 4. Inject small noise to support/lifestyle products
def inject_noise(product_name, column_name):
    noise_options = {
        "Support_HL": [
            "Red Onion Oil", "Fenugreek Scalp Serum", "Hairfall Repair Combo"
        ],
        "Lifestyle_HL": [
            "Stress Yoga", "Scalp Steam", "Silk Pillowcase"
        ],
        "Support_DF": [
            "Neem Oil", "Anti-Dandruff Hair Mask", "Charcoal Shampoo"
        ],
        "Lifestyle_DF": [
            "Oiling Schedule", "Mild Conditioner", "Herbal Rinse"
        ]
    }
    return random.choice(noise_options[column_name])

# 5. Generate full dataset
n_rows = 28000
data = []
for _ in tqdm(range(n_rows)):
    user = generate_user_response()
    products = map_products(user)

    # Introduce noise randomly in support/lifestyle (5% chance)
    for key in products:
        if "Support" in key or "Lifestyle" in key:
            if products[key] != "Not Applicable" and random.random() < 0.05:
                products[key] = inject_noise(products[key], key)

    user.update(products)
    data.append(user)

# 6. Save to CSV
df = pd.DataFrame(data)
df.to_csv("responses_with_targets_noisy.csv", index=False)
print("✅ File saved as: responses_with_targets_noisy.csv")

100%|██████████| 28000/28000 [00:00<00:00, 241867.11it/s]

✅ File saved as: responses_with_targets_noisy.csv

In [2]:
import pandas as pd
import random
from tqdm import tqdm
import numpy as np

# 1. Define feature space
features = {
    "AgeGroup": ["18–29", "30–44", "45+"],
    "HairLoss": ["Yes", "No"],
    "Dandruff": ["Yes", "No"],
    "HairGreying": ["Yes", "No"],
    "HL_Duration": ["<3 months", "3–6 months", ">6 months"],
    "HL_Shedding": ["Rarely", "Occasionally", "Frequently"],
    "DF_Type": ["Powdery", "Flaky"],
    "DF_ItchyScalp": ["Rarely", "Frequently"],
    "GR_Duration": ["<3 months", "<1 year", "<1.5 years"],
    "GR_TreatmentType": ["Coloring/Keratin", "None"],
    "RegularUsage": ["Yes", "No"],
    "WashFrequency": ["Rarely", "2–3 times/week", "Frequently"],
    "TakesSupplements": ["Yes", "No"],
    "StressLevel": ["Rarely", "Occasionally", "Frequently"],
    "FamilyHistory": ["Yes", "No"]
}

# 2. Support/Lifestyle noise options
noise_options = {
    "Support_HL": ["Red Onion Oil", "Fenugreek Scalp Serum", "Hairfall Repair Combo"],
    "Lifestyle_HL": ["Stress Yoga", "Scalp Steam", "Silk Pillowcase"],
    "Support_DF": ["Neem Oil", "Anti-Dandruff Hair Mask", "Charcoal Shampoo"],
    "Lifestyle_DF": ["Oiling Schedule", "Mild Conditioner", "Herbal Rinse"],
    "Primary_HL": ["Amla Hair Tonic", "Biotin Spray"],
    "Primary_DF": ["Apple Cider Rinse", "Coal Tar Shampoo"],
    "Primary_GR": ["Henna Oil", "Curry Leaf Capsules"]
}

# 3. Sample generation
def generate_user_response():
    return {k: random.choice(v) for k, v in features.items()}

# 4. Product mapping with slight randomness
def map_products(user):
    # Hair Loss
    if user["HairLoss"] == "Yes":
        duration = user["HL_Duration"]
        if duration == "<3 months":
            primary_hl = random.choice(["Redensyl + Biotin Combo Serum", "Redensyl Only"])
            support_hl = "Shampoo + Conditioner for Hairfall"
        elif duration == "3–6 months":
            primary_hl = "Redensyl + Biotin + Mild Minoxidil (Pilgrim, Be Bodywise)"
            support_hl = "DHT Blocker Shampoo + Conditioner"
        else:
            primary_hl = "Minoxidil 5% Foam + Redensyl + Microneedling"
            support_hl = "DHT Blocker + Supplements"
        lifestyle_hl = "Scalp Massage, Diet Improvement"
    else:
        primary_hl = support_hl = lifestyle_hl = "Not Applicable"

    # Dandruff
    if user["Dandruff"] == "Yes":
        if user["DF_Type"] == "Powdery" and user["DF_ItchyScalp"] == "Frequently":
            primary_df = "Ketoconazole + Salicylic Acid Shampoo"
            support_df = "Tea Tree Scalp Serum"
        else:
            primary_df = "ZPTO + pH Balancing Anti-Dandruff Shampoo"
            support_df = "Aloe Vera + Niacinamide Serum"
        lifestyle_df = "Avoid Hot Water, Gentle Shampoo"
    else:
        primary_df = support_df = lifestyle_df = "Not Applicable"

    # Greying
    if user["HairGreying"] == "Yes":
        if user["GR_TreatmentType"] == "Coloring/Keratin":
            primary_gr = "Hair Strengthening Oil + Amla Tablets"
        elif user["GR_Duration"] == "<3 months":
            primary_gr = "Vitamin B12 + Biotin Gummies"
        elif user["GR_Duration"] == "<1 year":
            primary_gr = "Melanin Boost Hair Oil"
        else:
            primary_gr = "Anti-Grey Hair Serum + Vitamin Supplements"
    else:
        primary_gr = "Not Applicable"

    return {
        "Primary_HL": primary_hl,
        "Support_HL": support_hl,
        "Lifestyle_HL": lifestyle_hl,
        "Primary_DF": primary_df,
        "Support_DF": support_df,
        "Lifestyle_DF": lifestyle_df,
        "Primary_GR": primary_gr
    }

# 5. Inject random noise
def add_random_noise(products, noise_chance=0.10):
    for col in products:
        if products[col] != "Not Applicable" and random.random() < noise_chance:
            if col in noise_options:
                products[col] = random.choice(noise_options[col])
    return products

# 6. Add mislabels to simulate human error (~2%)
def introduce_mislabel(products):
    if random.random() < 0.02:
        target_cols = [k for k in products if products[k] != "Not Applicable"]
        if target_cols:
            col = random.choice(target_cols)
            if col in noise_options:
                products[col] = random.choice(noise_options[col])
    return products

# 7. Dataset creation
n_rows = 28000
data = []

for _ in tqdm(range(n_rows)):
    user = generate_user_response()

    # Flip feature to simulate real-world data inconsistency (~2%)
    if random.random() < 0.02:
        flip_feature = random.choice(list(features.keys()))
        user[flip_feature] = random.choice(features[flip_feature])

    products = map_products(user)
    products = add_random_noise(products)
    products = introduce_mislabel(products)

    user.update(products)
    data.append(user)

# 8. Save
df = pd.DataFrame(data)
df.to_csv("responses_with_targets_noisy.csv", index=False)
print("✅ File saved as: responses_with_targets_noisy.csv")

100%|██████████| 28000/28000 [00:00<00:00, 188770.75it/s]

✅ File saved as: responses_with_targets_noisy.csv